print(".............................") 
print(".         ppppppppp         .") 
print(".      pp           pp      .") 
print(".     pp             pp     .") 
print(".    pp    PP   PP    pp    .") 
print(".   pp     PP   PP     pp   .") 
print(".   pp                 pp   .") 
print(".   pp  PP         PP  pp   .") 
print(".    pp   PP     PP   pp    .") 
print(".     pp    PPPPP   pp      .") 
print(".       pp        pp        .")
print(".          pppppp           .")